CREATE TABLE IF NOT EXISTS "movies" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT,
	"duration_min" INTEGER,
	"synopsis" TEXT,
	PRIMARY KEY("id")
);

CREATE INDEX "movies_index_0"
ON "movies" ("name");

CREATE TABLE IF NOT EXISTS "seats" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"number" TEXT,
	"id_auditorium" INTEGER,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "auditoriums" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT,
	"capacity" INTEGER,
	"is_available" BOOLEAN,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "users" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT,
	"email" TEXT,
	"password_hash" TEXT,
	"is_active" BOOLEAN,
    "role" TEXT,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "tickets" (
	"id" UUID PRIMARY KEY,
	"id_user" INTEGER NULL,
	"id_showtime" INTEGER,
	"status" TEXT,
	"id_seat" INTEGER,
	"email" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "showtimes" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_movie" INTEGER,
	"id_auditorium" INTEGER,
	"start_time" TIMESTAMP,
	PRIMARY KEY("id")
);

-- Seats belong to Auditoriums
ALTER TABLE "seats"
ADD FOREIGN KEY("id_auditorium") REFERENCES "auditoriums"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Tickets belong to Users
ALTER TABLE "tickets"
ADD FOREIGN KEY("id_user") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Showtimes belong to Auditoriums
ALTER TABLE "showtimes"
ADD FOREIGN KEY("id_auditorium") REFERENCES "auditoriums"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Showtimes belong to Movies
ALTER TABLE "showtimes"
ADD FOREIGN KEY("id_movie") REFERENCES "movies"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Tickets belong to Seats (This one was already correct!)
ALTER TABLE "tickets"
ADD FOREIGN KEY("id_seat") REFERENCES "seats"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Tickets belong to Showtimes
ALTER TABLE "tickets"
ADD FOREIGN KEY("id_showtime") REFERENCES "showtimes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Tickets should have a unique showtime and seat
ALTER TABLE "tickets"
ADD CONSTRAINT unique_showtime_seat
UNIQUE ("id_showtime", "id_seat");

-- First, drop the old constraint (assuming it was named something like this, check your DB for the exact name if it fails)
ALTER TABLE "tickets" DROP CONSTRAINT IF EXISTS "tickets_check";

-- Add the new, ultra-smart constraint
ALTER TABLE "tickets"
ADD CONSTRAINT "require_identity_on_checkout"
CHECK (
    ("status" = 'HOLD') -- If it's just held, allow nulls!
    OR
    ("status" = 'SOLD' AND ("id_user" IS NOT NULL OR "email" IS NOT NULL)) -- If sold, demand identity!
);
