CREATE TABLE IF NOT EXISTS "movies" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT,
	"duration_min" INTEGER,
	"synopsis" TEXT,
	PRIMARY KEY("id")
);

CREATE INDEX "movies_index_0"
ON "movies" ("name");

CREATE TABLE IF NOT EXISTS "seats" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"number" TEXT,
	"id_auditorium" INTEGER,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "auditoriums" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT,
	"capacity" INTEGER,
	"is_available" BOOLEAN,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "users" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT,
	"email" TEXT,
	"password_hash" TEXT,
	"is_active" BOOLEAN,
    "role" TEXT,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "tickets" (
	"id" UUID NOT NULL UNIQUE,
	"id_user" INTEGER,
	"id_showtime" INTEGER,
	"status" TEXT,
	"id_seat" INTEGER,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "showtimes" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_movie" INTEGER,
	"id_auditorium" INTEGER,
	"start_time" TIMESTAMP,
	PRIMARY KEY("id")
);

-- Seats belong to Auditoriums
ALTER TABLE "seats"
ADD FOREIGN KEY("id_auditorium") REFERENCES "auditoriums"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Tickets belong to Users
ALTER TABLE "tickets"
ADD FOREIGN KEY("id_user") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Showtimes belong to Auditoriums
ALTER TABLE "showtimes"
ADD FOREIGN KEY("id_auditorium") REFERENCES "auditoriums"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Showtimes belong to Movies
ALTER TABLE "showtimes"
ADD FOREIGN KEY("id_movie") REFERENCES "movies"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Tickets belong to Seats (This one was already correct!)
ALTER TABLE "tickets"
ADD FOREIGN KEY("id_seat") REFERENCES "seats"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Tickets belong to Showtimes
ALTER TABLE "tickets"
ADD FOREIGN KEY("id_showtime") REFERENCES "showtimes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Tickets should have a unique showtime and seat
ALTER TABLE "tickets"
ADD CONSTRAINT unique_showtime_seat
UNIQUE ("id_showtime", "id_seat");
