apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudcinema-dependencies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://valkey.io/valkey-helm/'
    chart: valkey
    targetRevision: '*'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudcinema-rabbitmq-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rabbitmq/cluster-operator'
    targetRevision: main
    path: config/installation
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rabbitmq-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudcinema-rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<tu-usuario>/<tu-repo-manifiestos>'
    targetRevision: main
    path: rabbitmq
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
