apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudcinema-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'
    targetRevision: 28.0.7
    chart: redis
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
