apiVersion: batch/v1
kind: Job
metadata:
  name: migrator
  annotations:
      argocd.argoproj.io/hook: Sync
      argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: migrator
          image: urielmt343/cinema_migrator:latest
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: secret-store
      restartPolicy: Never
