apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: urielmt343/cloudcinema-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/letsencrypt/live/cinema-cloud.com
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: nginx-tls
            items:
              - key: tls.crt
                path: fullchain.pem
              - key: tls.key
                path: privkey.pem
