apiVersion: v1
kind: Secret
metadata:
  name: secret-store-example
type: Opaque
stringData:
  POSTGRES_VERSION: "XX-alpine"
  POSTGRES_PORT: "XXXX"
  POSTGRES_HOST_PORT: "XXXX"
  POSTGRES_USER: "PG user"
  POSTGRES_PASSWORD: "Your secret password"
  POSTGRES_DB: "cinema"
  DATABASE_HOST: "postgres"
  REDIS_VERSION: "X.X-alpine"
  REDIS_PORT: "XXXX"
  RABBITMQ_VERSION: "4.2-management-alpine"
  AMQP_PORT: "XXXX"
  MANAGEMENT_UI_PORT: "XXXXX"
  API_PORT: "XXXX"
  GO_VERSION: "X.XX.X-alpineX.XX"
